### PR TITLE
Md to Mat upgrade

### PR DESCRIPTION
**Pull request by msmirnov85**
Hi @tarlepp ! #15 
In this pull request we migrated Md prefixes to Mat so that the library works correctly with newer versions of Angular Material(2.0.0-beta.12).
Also we fixed package.json configuration to make it work on Windows systems (we also tested it in MacOS).

### CODE REVIEW

**Comment by shoudaos** [comment]
@tarlepp Will you merge this PR?

**Comment by tarlepp** [comment]
@shoudaos sorry been so busy @work so didn't have time to take a look of your PR - I'll try to get some time for this weekend.

**Comment by ydock1** [comment]
@tarlepp  we would appreciate if you could merge this PR =D

**Comment by tarlepp** [comment]
Hmm, I need more time - could someone of @protacon/employees help with this one ?

**Comment by Tefofo** [comment]
Hi @tarlepp,
Are you able to merge this? We are trying to use the module in our codebase.
It will be very helpful if this can be done.

**Comment by tarlepp** [comment]
@Tefofo sorry haven't had really time to do this - too much work and other stuff. But luckily my summer holiday is starting after tomorrow, so maybe then I could have some time for this - but I don't promise anything.

And for that reason I  pinged @protacon/employees if there was someone who could look this, but seems like no :(

**Comment by Tefofo** [comment]
Thanks @tarlepp, will check again once you have made the changes.

**Pull request closed without merging**
